# Chapter 2 - NumPy
Prepared by Dr. N. Ali Saoucha
Associate Professor A
University of Algiers (nalisaoucha@gmail.com)

In [1]:
import numpy as np

# NumPy Array Creation

In [2]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4]]
list3 = [[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
print(type(arr1), type(arr2), type(arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(1, 4)
(3, 4)


In [4]:
arr4 = np.linspace(0, 10, 5)
print(arr4)

[ 0.   2.5  5.   7.5 10. ]


# Accessing Array Elements in NumPy

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[2])
print(arr1[-1])

3
5


In [6]:
arr2 = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
print(arr2[0])
print(arr2[0][1])
print(arr2[0,1])

['a' 'b' 'c']
b
b


In [7]:
arr3 = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(arr3[1:6])
print(arr3[1:6:2])
arr4 = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [100, 200, 300, 400, 500]])
print(arr4[0:2, 2:4])



['b' 'c' 'd' 'e' 'f']
['b' 'd' 'f']
[[ 3  4]
 [30 40]]


# ndarray Methods

In [ ]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr1.sum())
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))

36
[ 6  8 10 12]
[10 26]


In [9]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = arr2.reshape((3, 2))
print(arr2)
print(reshaped_array)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr3 = np.array([1, 2, 3, 4, 5])
reshaped_array_2 = arr3.reshape((1, -1))
print(arr3)
print(reshaped_array_2)

[1 2 3 4 5]
[[1 2 3 4 5]]


# NumPy Functions

## concatenate()

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
combined_array = np.concatenate((arr1, arr2))
print(combined_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr3 = np.array([[9], [10], [11], [12]])
combined_array = np.concatenate((combined_array, arr3), axis=1)
print(combined_array)

[[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]
 [ 7  8 12]]


## Wrapper Functions

In [ ]:
arr4 = np.array([1, 2, 3, 4, 5, 6])
reshaped1 = arr4.reshape((2,-1))
print(reshaped1)
reshaped2 = np.reshape(arr4, (2, -1))
print(reshaped2)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
